# Generated by Django 3.2.5 on 2021-11-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripttion', models.TextField(blank=True, max_length=500, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='Award/')),
            ],
        ),
    ]
