# Generated by Django 3.2.5 on 2021-11-01 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='descripttion',
            new_name='description',
        ),
    ]
