# Generated by Django 3.2.5 on 2021-11-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutApp', '0002_rename_descripttion_company_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='photo',
            new_name='photo0',
        ),
        migrations.AddField(
            model_name='company',
            name='missionvision',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='Award/'),
        ),
    ]
