# Generated by Django 2.2.4 on 2022-01-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutApp', '0004_developmenthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': '关于我们', 'verbose_name_plural': '关于我们'},
        ),
        migrations.AlterModelOptions(
            name='developmenthistory',
            options={'verbose_name': '历程简介', 'verbose_name_plural': '历程简介'},
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='公司简介'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='missionvision',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='使命与愿景'),
        ),
        migrations.AlterField(
            model_name='company',
            name='photo0',
            field=models.ImageField(blank=True, upload_to='Award/', verbose_name='顶部广告图'),
        ),
        migrations.AlterField(
            model_name='company',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='Award/', verbose_name='中间广告图'),
        ),
        migrations.AlterField(
            model_name='developmenthistory',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='发展历程'),
        ),
        migrations.AlterField(
            model_name='developmenthistory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='developmenthistory',
            name='year',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='年份'),
        ),
    ]
