# Generated by Django 2.2.4 on 2022-03-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0004_auto_20220303_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_file',
            field=models.FileField(blank=True, upload_to='Award/', verbose_name='产品手册'),
        ),
    ]
