# Generated by Django 3.2.5 on 2021-11-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.TextField(blank=True, max_length=500, null=True)),
                ('tel1', models.TextField(blank=True, max_length=500, null=True)),
                ('tel2', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
