# Generated by Django 3.2.5 on 2021-11-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0002_contactmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmethod',
            name='address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contactmethod',
            name='email',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contactmethod',
            name='qq1',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contactmethod',
            name='qq2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contactmethod',
            name='url',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
