# Generated by Django 3.2.5 on 2021-11-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0003_auto_20211111_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmethod',
            name='title',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
