# Generated by Django 3.2.5 on 2021-11-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0004_contactmethod_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=500, null=True)),
                ('name1', models.TextField(blank=True, max_length=500, null=True)),
                ('title1', models.TextField(blank=True, max_length=500, null=True)),
                ('photo1', models.ImageField(blank=True, upload_to='Award/')),
                ('name2', models.TextField(blank=True, max_length=500, null=True)),
                ('title2', models.TextField(blank=True, max_length=500, null=True)),
                ('photo2', models.ImageField(blank=True, upload_to='Award/')),
                ('name3', models.TextField(blank=True, max_length=500, null=True)),
                ('title3', models.TextField(blank=True, max_length=500, null=True)),
                ('photo3', models.ImageField(blank=True, upload_to='Award/')),
            ],
        ),
    ]
