# Generated by Django 3.2.5 on 2021-11-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynew',
            name='img',
            field=models.ImageField(blank=True, upload_to='Award/', verbose_name='缩略图'),
        ),
    ]
